### PR TITLE
Add linter to project

### PR DESCRIPTION
**Pull request by grizio**
There are lots of potential errors due to developer mistake (`=` instead of `==` or better `===`, type coercion, etc.).
To add quality to code and avoid these kind of issues, we add a linter.

This commit does the following:

- Add eslint with standard code styles (could be improved further)

Please look at commits for more information.

### CODE REVIEW

**Comment by grizio** [comment]
It does not correct all issues because some of them could be harmful (eg: `==` vs `===`). But at least it will bring some quality to new code.

**Comment by alex3144** [comment]
hello,
I do not add linter because the code is still not enough "clean" and enough standardized to add one. but thanks anyway when it will be done we will add one in the tests in addition to the project

**Comment by grizio** [comment]
I understand, however bugs still coming in new code. I never saw a code going cleaner if there was not a tool to do so.
I did not change the CI (contrary the name of my branch) because we need to standardize it as you said.

**Comment by DataPlayers** [comment]
ok thx for this add I copy/past eslintrc and script in new version for prevent conflict between our 2 versions

**Comment by grizio** [comment]
PR now useless.

**Pull request closed without merging**
